version: '3.1'

services:
  registry:
    container_name: registry
    network_mode: default
    image: registry:2
    restart: always
    ports:
      - 5000:5000
    volumes: 
      - ./registry/:/var/lib/registry
    