version: '3'

services:
  mongod:
    image: mongo:3.4-xenial
    restart: always
    # volumes: 
    #   - "./data/:/data/db"
    # ports: 
    #   - "27017:27017"
    networks:
      - xunfeng

  xunfeng:
    # image: harbor.querycap.com/rk-devops/xunfeng:0.0.8-mongo-slim
    image: bluesky4cn/xunfeng:0.1
    environment: 
      - MONGO_HOST=mongod
      # - MONGO_PORT=27017
    ports: 
      - 19090:80
    networks:
      - xunfeng


networks:
  xunfeng:
    ipam:
      driver: default
      config:
        - subnet: "169.254.99.0/24"
