[template]
src = "myapp-nginx.tmpl"
dest = "output/myapp-nginx.conf"
owner = "nginx"
mode = "0644"
keys = [
  "/nginx/services"
]

check_cmd = "/usr/sbin/nginx -t -c /etc/nginx/nginx.conf"
reload_cmd = "/usr/sbin/nginx -s reload"


reload_cmd (string) - The command to reload config.
check_cmd (string) - The command to check config. Use {{.src}} to reference the rendered source template.