version: '3.1'

services:
  db:
    image: mysql:5.7
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: YOUR_PASSWORD
    ports:
      - 60333:3306
    network_mode: default

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    network_mode: default
