version: '3.1'

services:
  nginx:
    image: nginx:1.15-alpine
    network_mode: default
    restart: always
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf
      # - /Users/tangxin/Documents/QueryCAP/项目组/智慧清徐/域名证书/:/etc/nginx/conf.d/
      - ./ssl/server.pem:/etc/nginx/conf.d/server.pem
      - ./ssl/server-key.pem:/etc/nginx/conf.d/server-key.pem
      - ./index.html:/usr/share/html/nginx/index.html
    ports:
      - 8443:443
      - 8080:80
