version: '3.1'

services:
  redis:
    # https://hub.docker.com/r/bitnami/redis
    image: 'bitnami/redis:5.0.5'
    environment:
      # - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PASSWORD=YOUR_PASSWORD
    ports:
      - '6379:6379'
    # volumes:
      # - /path/to/your_redis.conf:/opt/bitnami/redis/etc/redis.conf
      # - /path/to/redis-persistence:/bitnami/redis/data