version: '3.1'

# nginx 正向代理

services:
  nginx:
    network_mode: default
    # image: tangx/nginx:alpine-1.17-http_proxy-v2 
    # image: tangx/nginx:1.17-alpine_ngx-http-proxy
    image: tangx/nginx:alpine-1.17-http_proxy-4-mini
    restart: always
    volumes:
      - ./default-http-proxy.conf:/etc/nginx/conf.d/default.conf
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      # - 50443:443
      - 50080:80

