version: '3.1'

services:
  db:
    network_mode: default
    image: redis:5.0.2-alpine3.8
    # command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
    - 6379:6379