version: '3.1'

services:
  zabbix:
    networks: 
      - zabbix_net
    image: zabbix/zabbix-server-pgsql:ubuntu-4.2.6
    # image: zabbix/zabbix-server-pgsql:alpine-4.2.6
    restart: always
    ports:
      - 10051:10051
    environment:
      DB_SERVER_HOST: 192.168.100.100
      DB_SERVER_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: DB_PASSWD
      POSTGRES_DB: zabbix
      ZBX_ENABLE_SNMP_TRAPS: "true"

# docker run --name some-zabbix-web-nginx-pgsql -e DB_SERVER_HOST="some-postgres-server" -e POSTGRES_USER="some-user" -e POSTGRES_PASSWORD="some-password" -e ZBX_SERVER_HOST="some-zabbix-server" -e PHP_TZ="some-timezone" -d zabbix/zabbix-web-nginx-pgsql:tag

  nginx:
    networks: 
      - zabbix_net
    image: zabbix/zabbix-web-nginx-pgsql:ubuntu-4.2.6
    ports:
      - 50080:80
    environment:
      DB_SERVER_HOST: 192.168.100.100
      DB_SERVER_PORT: 5432
      POSTGRES_USER: root
      POSTGRES_PASSWORD: DB_PASSWD
      POSTGRES_DB: zabbix
      ZBX_SERVER_HOST: zabbix
      ZBX_SERVER_PORT: 10051
      PHP_TZ: "Asia/Shanghai"

networks:
  zabbix_net:
    ipam:
      driver: default
      config:
        - subnet: "169.254.200.0/24"





# docker run --name some-zabbix-server-pgsql -e DB_SERVER_HOST="some-postgres-server" -e POSTGRES_USER="some-user" -e POSTGRES_PASSWORD="some-password" -d zabbix/zabbix-server-pgsql:tag
